DOMAIN = "fireboard"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
API_BASE = "https://fireboard.io/api/v1"
LOGIN_URL = "https://fireboard.io/api/rest-auth/login/"
USER_AGENT = "HomeAssistant FireBoard Integration"
